name: CD Pipeline (Simulation)

on:
 push:
  branches:
   - master

jobs:
 deploy:
  name: Simulate Deployment
  runs-on: ubuntu-lastest

  steps:
   - name: Checkout code
     uses: action/checkout@v4

   - name: Show deployment environment
   - run: |
      echo "Environment : Production"
      echo "Branch : main"
      echo "Commit SHA : $GITHUB_SHA"

   - name: Simulate build application...
     run: |
      echo "Building application..."
      sleep 3
      echo "Build success!"

   - name: Simulate deployment
     run: |
      echo "Deploying application to server..."
      sleep 3
      echo "Deployment completed successfully!"

   - name: Deployment finished
     run: echo "CD Pipeline finished successfully"
