name: Matrix CI Pipeline

on:
 push:
  branches:
    - master
    - feature-readme

jobs:
 build:
  strategy:
   matrix:
    os: [ubuntu-latest, windows-latest, macos-latest]

  runs-on: ubuntu-latest

  steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Show OS info
     run: |
       echo "Running on OS"
       uname -a || ver

   - name: Show current directory
     run: pwd

   - name: List repository files
     run: ls -la

   - name: Production only step
     if: github.ref == 'refs/heads/master'
     run: echo "Ini hanya berjalan di branch master (production)"
